name: demo-1st-code

on:
  push:
   branches:        
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: check out code
        uses: actions/checkout@v2      
      - name: setup Python env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install liberaries
        run: |
            cd function
            python -m pip install  --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create Zip Bundle
        run: |
           cd function
            zip -r ../${{ github.sha }}.zip .

      - name: Archive Artifect
        uses: actions/upload-artifect@v2
        with:
          name: zipp-bundled
          path: ${{ github.sha }}.zip 
